### ISSUE TITLE
Stained glass render error

### ISSUE THREAD

**Issue by Pleune** [sixthsurge/photon#264]
### What happened?

All stained glass in the world renders with a broken texture. This seems to only happen with photon. It may be relevant that I am on Intel Arc.

See comparision between latest photon main, and lux.

![image](https://github.com/user-attachments/assets/7e6e191c-6976-4ad3-8b18-72c990176715)
![image](https://github.com/user-attachments/assets/7a8c94c1-060c-495e-9e7b-8517a58f8d32)

Interestingly, the photon shadows still show the correct glass texture

### Minecraft Version

1.20.2

### Which shader mod are you using?

Iris

### Shader mod version

Tested with every version supported for 1.21

### Shader settings

```conf
I have tried enabling and disabling every option, and they all have zero effect.
```

**Comment by Patomosm** [comment]
Hallo. I think it's an Intel issue because I don't have it with an AMD cpu.
![Minecraft Screenshot 2025 01 11 - 22 21 48 81](https://github.com/user-attachments/assets/9131095d-3fe7-476b-a499-34b80adeef97)

[The resource Pack is here](https://legacy.curseforge.com/members/patomosm/projects)

**Comment by ilux-git** [comment]
Hello! I have encountered the same problem. Actually, as it turned out, it affects not only stained glass and stained glass panes, but also Nether Portal blocks (on the 1st photo). Initially I couldn't find a solution to this problem on the internet, but I liked Photon so much that I didn't want to just use another shader. So I decided to look into it myself. Turns out the problem lies in the code for translucent objects. The path to the file is _shaders/program/gbuffer/translucent.glsl_ for v1.0a and _shaders/program/fbuffers_all_translucent.vsh for v1.1_. On the 2nd photo (code) you can see that if you change the code for **uv** (line 92 for v1.0a and line 89 for v1.1), the **problem is solved** (photo 3). 

![Image](https://github.com/user-attachments/assets/d9eb8849-2204-4587-a687-f9daf537b624)

![Image](https://github.com/user-attachments/assets/f58e5825-c44e-4b4b-991d-39e372081036)

![Image](https://github.com/user-attachments/assets/e28e553a-2c4b-405e-ad63-9aeeec8b63a1)

May sixthsurge forgive me for doing surgery on his code :) )

P.S. I am on intel too (laptop with Intel UHD integrated graphics) so I think it is really an Intel thing

**Comment by Pleune** [comment]
Wow that fixes it for me! Now the change is in `gbuffers_all_translucent.vsh` https://github.com/sixthsurge/photon/blob/8201f7889eb05aa90e7325e436b3fc14a7b1f160/shaders/program/gbuffers_all_translucent.vsh#L89

![Image](https://github.com/user-attachments/assets/995963d9-6690-4b05-92ed-4d96fdb8dfe3)

![Image](https://github.com/user-attachments/assets/78b53aa2-7687-41ae-89aa-cf2c183c4689)

**Comment by DannyDevPro** [comment]
> 哇，这为我解决了！现在变化来了`gbuffers_all_translucent.vsh`
> 
> [photon/shaders/program/gbuffers_all_translucent.vsh](https://github.com/sixthsurge/photon/blob/8201f7889eb05aa90e7325e436b3fc14a7b1f160/shaders/program/gbuffers_all_translucent.vsh#L89)
> 
> 89 号线 在[编号 8201F78](/sixthsurge/photon/commit/8201f7889eb05aa90e7325e436b3fc14a7b1f160)
> 
> uv = mat2（gl_TextureMatrix[0]） * gl_MultiTexCoord0.xy + gl_TextureMatrix[0][3].xy;
> ![Image](https://github.com/user-attachments/assets/995963d9-6690-4b05-92ed-4d96fdb8dfe3)
> 
> ![Image](https://github.com/user-attachments/assets/78b53aa2-7687-41ae-89aa-cf2c183c4689)

But on my PC，it dosn‘t render correctly

![Image](https://github.com/user-attachments/assets/9f5dd0da-bb57-4bc5-8c53-ce631a7ffb74)

**Comment by ilux-git** [comment]
> But on my PC，it dosn‘t render correctly

Hello! Is your shaders' code line 89 in _shaders/program/gbuffers_all_translucent.vsh_ looks exactly like this?:
uv 			  = (gl_TextureMatrix[0] * vec4(gl_MultiTexCoord0.xy, 0.0, 1.0)).xy;
If yes, then do you use any visual mods apart from Iris and Sodium?

**Comment by ScorpionChen** [comment]
this bug still happens till now，and this metod still works, thanks

**Comment by sixthsurge** [comment]
Wow thanks for finding the fix
